language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'

script:
    - curl -L -o reflectivedoc.php https://www.monperrus.net/martin/reflectivedoc.php.txt
    - curl -L -o gakowiki-syntax.php https://www.monperrus.net/martin/gakowiki-syntax.php.txt
    - phpunit bibtexbrowser-test.php

sudo: false
